name: cd
on:
  push:
    branches:
      - main
jobs:
  vite:
    permissions:
      pages: write
      id-token: write
    uses: umts/shared-workflow-sandbox/.github/workflows/deploy-vite-app.yml@main

